#include "FXRbCommon.h"
/* Start stub implementations for class FXMemoryBuffer */

/* Start stub implementations for class FXRb4Splitter */
IMPLEMENT_FXOBJECT_STUBS(FXRb4Splitter)
IMPLEMENT_FXID_STUBS(FXRb4Splitter)
IMPLEMENT_FXDRAWABLE_STUBS(FXRb4Splitter)
IMPLEMENT_FXWINDOW_STUBS(FXRb4Splitter)

/* Start stub implementations for class FXRb7Segment */
IMPLEMENT_FXOBJECT_STUBS(FXRb7Segment)
IMPLEMENT_FXID_STUBS(FXRb7Segment)
IMPLEMENT_FXDRAWABLE_STUBS(FXRb7Segment)
IMPLEMENT_FXWINDOW_STUBS(FXRb7Segment)

/* Start stub implementations for class FXRbAccelTable */
IMPLEMENT_FXOBJECT_STUBS(FXRbAccelTable)

/* Start stub implementations for class FXRbApp */
IMPLEMENT_FXOBJECT_STUBS(FXRbApp)
IMPLEMENT_FXAPP_STUBS(FXRbApp)

/* Start stub implementations for class FXRbArrowButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbArrowButton)
IMPLEMENT_FXID_STUBS(FXRbArrowButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbArrowButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbArrowButton)

/* Start stub implementations for class FXRbBMPIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbBMPIcon)
IMPLEMENT_FXID_STUBS(FXRbBMPIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbBMPIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbBMPIcon)

/* Start stub implementations for class FXRbBMPImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbBMPImage)
IMPLEMENT_FXID_STUBS(FXRbBMPImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbBMPImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbBMPImage)

/* Start stub implementations for class FXRbBitmap */
IMPLEMENT_FXOBJECT_STUBS(FXRbBitmap)
IMPLEMENT_FXID_STUBS(FXRbBitmap)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbBitmap)
IMPLEMENT_FXBITMAP_STUBS(FXRbBitmap)

/* Start stub implementations for class FXRbBitmapFrame */
IMPLEMENT_FXOBJECT_STUBS(FXRbBitmapFrame)
IMPLEMENT_FXID_STUBS(FXRbBitmapFrame)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbBitmapFrame)
IMPLEMENT_FXWINDOW_STUBS(FXRbBitmapFrame)

/* Start stub implementations for class FXRbButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbButton)
IMPLEMENT_FXID_STUBS(FXRbButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbButton)

/* Start stub implementations for class FXRbCURCursor */
IMPLEMENT_FXOBJECT_STUBS(FXRbCURCursor)
IMPLEMENT_FXID_STUBS(FXRbCURCursor)
IMPLEMENT_FXCURSOR_STUBS(FXRbCURCursor)

/* Start stub implementations for class FXRbCanvas */
IMPLEMENT_FXOBJECT_STUBS(FXRbCanvas)
IMPLEMENT_FXID_STUBS(FXRbCanvas)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbCanvas)
IMPLEMENT_FXWINDOW_STUBS(FXRbCanvas)

/* Start stub implementations for class FXRbCheckButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbCheckButton)
IMPLEMENT_FXID_STUBS(FXRbCheckButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbCheckButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbCheckButton)

/* Start stub implementations for class FXRbChoiceBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbChoiceBox)
IMPLEMENT_FXID_STUBS(FXRbChoiceBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbChoiceBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbChoiceBox)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbChoiceBox)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbChoiceBox)

/* Start stub implementations for class FXRbColorBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorBar)
IMPLEMENT_FXID_STUBS(FXRbColorBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbColorBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbColorBar)

/* Start stub implementations for class FXRbColorDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorDialog)
IMPLEMENT_FXID_STUBS(FXRbColorDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbColorDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbColorDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbColorDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbColorDialog)

/* Start stub implementations for class FXRbColorItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorItem)
IMPLEMENT_FXLISTITEM_STUBS(FXRbColorItem)

/* Start stub implementations for class FXRbColorList */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorList)
IMPLEMENT_FXID_STUBS(FXRbColorList)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbColorList)
IMPLEMENT_FXWINDOW_STUBS(FXRbColorList)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbColorList)
IMPLEMENT_FXLIST_STUBS(FXRbColorList)

/* Start stub implementations for class FXRbColorRing */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorRing)
IMPLEMENT_FXID_STUBS(FXRbColorRing)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbColorRing)
IMPLEMENT_FXWINDOW_STUBS(FXRbColorRing)

/* Start stub implementations for class FXRbColorSelector */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorSelector)
IMPLEMENT_FXID_STUBS(FXRbColorSelector)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbColorSelector)
IMPLEMENT_FXWINDOW_STUBS(FXRbColorSelector)

/* Start stub implementations for class FXRbColorWell */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorWell)
IMPLEMENT_FXID_STUBS(FXRbColorWell)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbColorWell)
IMPLEMENT_FXWINDOW_STUBS(FXRbColorWell)

/* Start stub implementations for class FXRbColorWheel */
IMPLEMENT_FXOBJECT_STUBS(FXRbColorWheel)
IMPLEMENT_FXID_STUBS(FXRbColorWheel)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbColorWheel)
IMPLEMENT_FXWINDOW_STUBS(FXRbColorWheel)

/* Start stub implementations for class FXRbComboBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbComboBox)
IMPLEMENT_FXID_STUBS(FXRbComboBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbComboBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbComboBox)

/* Start stub implementations for class FXRbComposite */
IMPLEMENT_FXOBJECT_STUBS(FXRbComposite)
IMPLEMENT_FXID_STUBS(FXRbComposite)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbComposite)
IMPLEMENT_FXWINDOW_STUBS(FXRbComposite)

/* Start stub implementations for class FXRbCursor */
IMPLEMENT_FXOBJECT_STUBS(FXRbCursor)
IMPLEMENT_FXID_STUBS(FXRbCursor)
IMPLEMENT_FXCURSOR_STUBS(FXRbCursor)

/* Start stub implementations for class FXRbDC */
IMPLEMENT_FXDC_STUBS(FXRbDC)

/* Start stub implementations for class FXRbDCPrint */
IMPLEMENT_FXDC_STUBS(FXRbDCPrint)

/* Start stub implementations for class FXRbDCWindow */
IMPLEMENT_FXDC_STUBS(FXRbDCWindow)

/* Start stub implementations for class FXRbDataTarget */
IMPLEMENT_FXOBJECT_STUBS(FXRbDataTarget)

/* Start stub implementations for class FXRbDebugTarget */
IMPLEMENT_FXOBJECT_STUBS(FXRbDebugTarget)

/* Start stub implementations for class FXRbDelegator */
IMPLEMENT_FXOBJECT_STUBS(FXRbDelegator)

/* Start stub implementations for class FXRbDial */
IMPLEMENT_FXOBJECT_STUBS(FXRbDial)
IMPLEMENT_FXID_STUBS(FXRbDial)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDial)
IMPLEMENT_FXWINDOW_STUBS(FXRbDial)

/* Start stub implementations for class FXRbDialogBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbDialogBox)
IMPLEMENT_FXID_STUBS(FXRbDialogBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDialogBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbDialogBox)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbDialogBox)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbDialogBox)

/* Start stub implementations for class FXRbDict */
IMPLEMENT_FXOBJECT_STUBS(FXRbDict)

/* Start stub implementations for class FXRbDirBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbDirBox)
IMPLEMENT_FXID_STUBS(FXRbDirBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDirBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbDirBox)
IMPLEMENT_FXTREELISTBOX_STUBS(FXRbDirBox)

/* Start stub implementations for class FXRbDirDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbDirDialog)
IMPLEMENT_FXID_STUBS(FXRbDirDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDirDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbDirDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbDirDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbDirDialog)

/* Start stub implementations for class FXRbDirItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbDirItem)
IMPLEMENT_FXTREEITEM_STUBS(FXRbDirItem,FXDirItem)

/* Start stub implementations for class FXRbDirList */
IMPLEMENT_FXOBJECT_STUBS(FXRbDirList)
IMPLEMENT_FXID_STUBS(FXRbDirList)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDirList)
IMPLEMENT_FXWINDOW_STUBS(FXRbDirList)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbDirList)
IMPLEMENT_FXTREELIST_STUBS(FXRbDirList)

/* Start stub implementations for class FXRbDirSelector */
IMPLEMENT_FXOBJECT_STUBS(FXRbDirSelector)
IMPLEMENT_FXID_STUBS(FXRbDirSelector)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDirSelector)
IMPLEMENT_FXWINDOW_STUBS(FXRbDirSelector)

/* Start stub implementations for class FXRbDockBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbDockBar)
IMPLEMENT_FXID_STUBS(FXRbDockBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDockBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbDockBar)
IMPLEMENT_FXDOCKBAR_STUBS(FXRbDockBar)

/* Start stub implementations for class FXRbDockHandler */
IMPLEMENT_FXOBJECT_STUBS(FXRbDockHandler)
IMPLEMENT_FXID_STUBS(FXRbDockHandler)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDockHandler)
IMPLEMENT_FXWINDOW_STUBS(FXRbDockHandler)

/* Start stub implementations for class FXRbDockSite */
IMPLEMENT_FXOBJECT_STUBS(FXRbDockSite)
IMPLEMENT_FXID_STUBS(FXRbDockSite)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDockSite)
IMPLEMENT_FXWINDOW_STUBS(FXRbDockSite)
IMPLEMENT_FXDOCKSITE_STUBS(FXRbDockSite)

/* Start stub implementations for class FXRbDockTitle */
IMPLEMENT_FXOBJECT_STUBS(FXRbDockTitle)
IMPLEMENT_FXID_STUBS(FXRbDockTitle)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDockTitle)
IMPLEMENT_FXWINDOW_STUBS(FXRbDockTitle)

/* Start stub implementations for class FXRbDocument */
IMPLEMENT_FXOBJECT_STUBS(FXRbDocument)

/* Start stub implementations for class FXRbDragCorner */
IMPLEMENT_FXOBJECT_STUBS(FXRbDragCorner)
IMPLEMENT_FXID_STUBS(FXRbDragCorner)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDragCorner)
IMPLEMENT_FXWINDOW_STUBS(FXRbDragCorner)

/* Start stub implementations for class FXRbDrawable */
IMPLEMENT_FXOBJECT_STUBS(FXRbDrawable)
IMPLEMENT_FXID_STUBS(FXRbDrawable)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDrawable)

/* Start stub implementations for class FXRbDriveBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbDriveBox)
IMPLEMENT_FXID_STUBS(FXRbDriveBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbDriveBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbDriveBox)
IMPLEMENT_FXLISTBOX_STUBS(FXRbDriveBox)

/* Start stub implementations for class FXRbFileDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbFileDialog)
IMPLEMENT_FXID_STUBS(FXRbFileDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbFileDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbFileDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbFileDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbFileDialog)

/* Start stub implementations for class FXRbIconDict */
IMPLEMENT_FXOBJECT_STUBS(FXRbIconDict)

/* Start stub implementations for class FXRbFileDict */
IMPLEMENT_FXOBJECT_STUBS(FXRbFileDict)
IMPLEMENT_FXFILEDICT_STUBS(FXRbFileDict)

/* Start stub implementations for class FXRbFileItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbFileItem)
IMPLEMENT_FXICONITEM_STUBS(FXRbFileItem,FXFileItem)

/* Start stub implementations for class FXRbFileList */
IMPLEMENT_FXOBJECT_STUBS(FXRbFileList)
IMPLEMENT_FXID_STUBS(FXRbFileList)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbFileList)
IMPLEMENT_FXWINDOW_STUBS(FXRbFileList)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbFileList)
IMPLEMENT_FXICONLIST_STUBS(FXRbFileList)

/* Start stub implementations for class FXRbFileSelector */
IMPLEMENT_FXOBJECT_STUBS(FXRbFileSelector)
IMPLEMENT_FXID_STUBS(FXRbFileSelector)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbFileSelector)
IMPLEMENT_FXWINDOW_STUBS(FXRbFileSelector)

/* Start stub implementations for class FXRbFoldingItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbFoldingItem)
IMPLEMENT_FXFOLDINGITEM_STUBS(FXRbFoldingItem)

/* Start stub implementations for class FXRbFoldingList */
IMPLEMENT_FXOBJECT_STUBS(FXRbFoldingList)
IMPLEMENT_FXID_STUBS(FXRbFoldingList)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbFoldingList)
IMPLEMENT_FXWINDOW_STUBS(FXRbFoldingList)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbFoldingList)
IMPLEMENT_FXFOLDINGLIST_STUBS(FXRbFoldingList)

/* Start stub implementations for class FXRbFont */
IMPLEMENT_FXOBJECT_STUBS(FXRbFont)
IMPLEMENT_FXID_STUBS(FXRbFont)
IMPLEMENT_FXFONT_STUBS(FXRbFont)

/* Start stub implementations for class FXRbFontDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbFontDialog)
IMPLEMENT_FXID_STUBS(FXRbFontDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbFontDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbFontDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbFontDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbFontDialog)

/* Start stub implementations for class FXRbFontSelector */
IMPLEMENT_FXOBJECT_STUBS(FXRbFontSelector)
IMPLEMENT_FXID_STUBS(FXRbFontSelector)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbFontSelector)
IMPLEMENT_FXWINDOW_STUBS(FXRbFontSelector)

/* Start stub implementations for class FXRbFrame */
IMPLEMENT_FXOBJECT_STUBS(FXRbFrame)
IMPLEMENT_FXID_STUBS(FXRbFrame)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbFrame)
IMPLEMENT_FXWINDOW_STUBS(FXRbFrame)

/* Start stub implementations for class FXRbGIFCursor */
IMPLEMENT_FXOBJECT_STUBS(FXRbGIFCursor)
IMPLEMENT_FXID_STUBS(FXRbGIFCursor)
IMPLEMENT_FXCURSOR_STUBS(FXRbGIFCursor)

/* Start stub implementations for class FXRbGIFIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbGIFIcon)
IMPLEMENT_FXID_STUBS(FXRbGIFIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbGIFIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbGIFIcon)

/* Start stub implementations for class FXRbGIFImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbGIFImage)
IMPLEMENT_FXID_STUBS(FXRbGIFImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbGIFImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbGIFImage)

/* Start stub implementations for class FXRbGLCanvas */
IMPLEMENT_FXOBJECT_STUBS(FXRbGLCanvas)
IMPLEMENT_FXID_STUBS(FXRbGLCanvas)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbGLCanvas)
IMPLEMENT_FXWINDOW_STUBS(FXRbGLCanvas)
IMPLEMENT_FXGLCANVAS_STUBS(FXRbGLCanvas)

/* Start stub implementations for class FXRbGLContext */
IMPLEMENT_FXOBJECT_STUBS(FXRbGLContext)
IMPLEMENT_FXID_STUBS(FXRbGLContext)

/* Start stub implementations for class FXRbGLObject */
IMPLEMENT_FXOBJECT_STUBS(FXRbGLObject)
IMPLEMENT_FXGLOBJECT_STUBS(FXRbGLObject)

/* Start stub implementations for class FXRbGLShape */
IMPLEMENT_FXOBJECT_STUBS(FXRbGLShape)
IMPLEMENT_FXGLOBJECT_STUBS(FXRbGLShape)
IMPLEMENT_FXGLSHAPE_STUBS(FXRbGLShape,FXGLShape)

/* Start stub implementations for class FXRbGLViewer */
IMPLEMENT_FXOBJECT_STUBS(FXRbGLViewer)
IMPLEMENT_FXID_STUBS(FXRbGLViewer)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbGLViewer)
IMPLEMENT_FXWINDOW_STUBS(FXRbGLViewer)
IMPLEMENT_FXGLCANVAS_STUBS(FXRbGLViewer)
IMPLEMENT_FXGLVIEWER_STUBS(FXRbGLViewer)

/* Start stub implementations for class FXRbGLVisual */
IMPLEMENT_FXOBJECT_STUBS(FXRbGLVisual)
IMPLEMENT_FXID_STUBS(FXRbGLVisual)

/* Start stub implementations for class FXRbGradientBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbGradientBar)
IMPLEMENT_FXID_STUBS(FXRbGradientBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbGradientBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbGradientBar)

/* Start stub implementations for class FXRbGroupBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbGroupBox)
IMPLEMENT_FXID_STUBS(FXRbGroupBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbGroupBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbGroupBox)

/* Start stub implementations for class FXRbHeaderItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbHeaderItem)
IMPLEMENT_FXHEADERITEM_STUBS(FXRbHeaderItem)

/* Start stub implementations for class FXRbHeader */
IMPLEMENT_FXOBJECT_STUBS(FXRbHeader)
IMPLEMENT_FXID_STUBS(FXRbHeader)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbHeader)
IMPLEMENT_FXWINDOW_STUBS(FXRbHeader)

/* Start stub implementations for class FXRbHorizontalFrame */
IMPLEMENT_FXOBJECT_STUBS(FXRbHorizontalFrame)
IMPLEMENT_FXID_STUBS(FXRbHorizontalFrame)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbHorizontalFrame)
IMPLEMENT_FXWINDOW_STUBS(FXRbHorizontalFrame)

/* Start stub implementations for class FXRbICOIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbICOIcon)
IMPLEMENT_FXID_STUBS(FXRbICOIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbICOIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbICOIcon)

/* Start stub implementations for class FXRbICOImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbICOImage)
IMPLEMENT_FXID_STUBS(FXRbICOImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbICOImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbICOImage)

/* Start stub implementations for class FXRbIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbIcon)
IMPLEMENT_FXID_STUBS(FXRbIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbIcon)

/* Start stub implementations for class FXRbIconItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbIconItem)
IMPLEMENT_FXICONITEM_STUBS(FXRbIconItem,FXIconItem)

/* Start stub implementations for class FXRbIconList */
IMPLEMENT_FXOBJECT_STUBS(FXRbIconList)
IMPLEMENT_FXID_STUBS(FXRbIconList)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbIconList)
IMPLEMENT_FXWINDOW_STUBS(FXRbIconList)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbIconList)
IMPLEMENT_FXICONLIST_STUBS(FXRbIconList)

/* Start stub implementations for class FXRbIconSource */
IMPLEMENT_FXOBJECT_STUBS(FXRbIconSource)
IMPLEMENT_FXICONSOURCE_STUBS(FXRbIconSource)

/* Start stub implementations for class FXRbId */
IMPLEMENT_FXOBJECT_STUBS(FXRbId)
IMPLEMENT_FXID_STUBS(FXRbId)

/* Start stub implementations for class FXRbImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbImage)
IMPLEMENT_FXID_STUBS(FXRbImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbImage)

/* Start stub implementations for class FXRbImageFrame */
IMPLEMENT_FXOBJECT_STUBS(FXRbImageFrame)
IMPLEMENT_FXID_STUBS(FXRbImageFrame)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbImageFrame)
IMPLEMENT_FXWINDOW_STUBS(FXRbImageFrame)

/* Start stub implementations for class FXRbImageView */
IMPLEMENT_FXOBJECT_STUBS(FXRbImageView)
IMPLEMENT_FXID_STUBS(FXRbImageView)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbImageView)
IMPLEMENT_FXWINDOW_STUBS(FXRbImageView)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbImageView)

/* Start stub implementations for class FXRbInputDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbInputDialog)
IMPLEMENT_FXID_STUBS(FXRbInputDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbInputDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbInputDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbInputDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbInputDialog)

/* Start stub implementations for class FXRbJPGIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbJPGIcon)
IMPLEMENT_FXID_STUBS(FXRbJPGIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbJPGIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbJPGIcon)

/* Start stub implementations for class FXRbJPGImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbJPGImage)
IMPLEMENT_FXID_STUBS(FXRbJPGImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbJPGImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbJPGImage)

/* Start stub implementations for class FXRbKnob */
IMPLEMENT_FXOBJECT_STUBS(FXRbKnob)
IMPLEMENT_FXID_STUBS(FXRbKnob)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbKnob)
IMPLEMENT_FXWINDOW_STUBS(FXRbKnob)

/* Start stub implementations for class FXRbLabel */
IMPLEMENT_FXOBJECT_STUBS(FXRbLabel)
IMPLEMENT_FXID_STUBS(FXRbLabel)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbLabel)
IMPLEMENT_FXWINDOW_STUBS(FXRbLabel)

/* Start stub implementations for class FXRbListItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbListItem)
IMPLEMENT_FXLISTITEM_STUBS(FXRbListItem)

/* Start stub implementations for class FXRbList */
IMPLEMENT_FXOBJECT_STUBS(FXRbList)
IMPLEMENT_FXID_STUBS(FXRbList)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbList)
IMPLEMENT_FXWINDOW_STUBS(FXRbList)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbList)
IMPLEMENT_FXLIST_STUBS(FXRbList)

/* Start stub implementations for class FXRbListBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbListBox)
IMPLEMENT_FXID_STUBS(FXRbListBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbListBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbListBox)
IMPLEMENT_FXLISTBOX_STUBS(FXRbListBox)

/* Start stub implementations for class FXRbMDIDeleteButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIDeleteButton)
IMPLEMENT_FXID_STUBS(FXRbMDIDeleteButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIDeleteButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIDeleteButton)

/* Start stub implementations for class FXRbMDIRestoreButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIRestoreButton)
IMPLEMENT_FXID_STUBS(FXRbMDIRestoreButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIRestoreButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIRestoreButton)

/* Start stub implementations for class FXRbMDIMinimizeButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIMinimizeButton)
IMPLEMENT_FXID_STUBS(FXRbMDIMinimizeButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIMinimizeButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIMinimizeButton)

/* Start stub implementations for class FXRbMDIMaximizeButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIMaximizeButton)
IMPLEMENT_FXID_STUBS(FXRbMDIMaximizeButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIMaximizeButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIMaximizeButton)

/* Start stub implementations for class FXRbMDIWindowButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIWindowButton)
IMPLEMENT_FXID_STUBS(FXRbMDIWindowButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIWindowButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIWindowButton)

/* Start stub implementations for class FXRbMDIMenu */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIMenu)
IMPLEMENT_FXID_STUBS(FXRbMDIMenu)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIMenu)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIMenu)
IMPLEMENT_FXPOPUP_STUBS(FXRbMDIMenu)

/* Start stub implementations for class FXRbMDIChild */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIChild)
IMPLEMENT_FXID_STUBS(FXRbMDIChild)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIChild)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIChild)
IMPLEMENT_FXMDICHILD_STUBS(FXRbMDIChild)

/* Start stub implementations for class FXRbMDIClient */
IMPLEMENT_FXOBJECT_STUBS(FXRbMDIClient)
IMPLEMENT_FXID_STUBS(FXRbMDIClient)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMDIClient)
IMPLEMENT_FXWINDOW_STUBS(FXRbMDIClient)
IMPLEMENT_FXMDICLIENT_STUBS(FXRbMDIClient)

/* Start stub implementations for class FXRbMainWindow */
IMPLEMENT_FXOBJECT_STUBS(FXRbMainWindow)
IMPLEMENT_FXID_STUBS(FXRbMainWindow)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMainWindow)
IMPLEMENT_FXWINDOW_STUBS(FXRbMainWindow)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbMainWindow)

/* Start stub implementations for class FXRbMatrix */
IMPLEMENT_FXOBJECT_STUBS(FXRbMatrix)
IMPLEMENT_FXID_STUBS(FXRbMatrix)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMatrix)
IMPLEMENT_FXWINDOW_STUBS(FXRbMatrix)

/* Start stub implementations for class FXRbMenuBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuBar)
IMPLEMENT_FXID_STUBS(FXRbMenuBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuBar)
IMPLEMENT_FXDOCKBAR_STUBS(FXRbMenuBar)

/* Start stub implementations for class FXRbMenuButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuButton)
IMPLEMENT_FXID_STUBS(FXRbMenuButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuButton)

/* Start stub implementations for class FXRbMenuCaption */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuCaption)
IMPLEMENT_FXID_STUBS(FXRbMenuCaption)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuCaption)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuCaption)

/* Start stub implementations for class FXRbMenuCascade */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuCascade)
IMPLEMENT_FXID_STUBS(FXRbMenuCascade)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuCascade)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuCascade)

/* Start stub implementations for class FXRbMenuCheck */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuCheck)
IMPLEMENT_FXID_STUBS(FXRbMenuCheck)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuCheck)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuCheck)

/* Start stub implementations for class FXRbMenuCommand */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuCommand)
IMPLEMENT_FXID_STUBS(FXRbMenuCommand)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuCommand)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuCommand)

/* Start stub implementations for class FXRbMenuPane */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuPane)
IMPLEMENT_FXID_STUBS(FXRbMenuPane)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuPane)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuPane)
IMPLEMENT_FXPOPUP_STUBS(FXRbMenuPane)

/* Start stub implementations for class FXRbMenuRadio */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuRadio)
IMPLEMENT_FXID_STUBS(FXRbMenuRadio)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuRadio)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuRadio)

/* Start stub implementations for class FXRbMenuSeparator */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuSeparator)
IMPLEMENT_FXID_STUBS(FXRbMenuSeparator)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuSeparator)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuSeparator)

/* Start stub implementations for class FXRbMenuTitle */
IMPLEMENT_FXOBJECT_STUBS(FXRbMenuTitle)
IMPLEMENT_FXID_STUBS(FXRbMenuTitle)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMenuTitle)
IMPLEMENT_FXWINDOW_STUBS(FXRbMenuTitle)

/* Start stub implementations for class FXRbMessageBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbMessageBox)
IMPLEMENT_FXID_STUBS(FXRbMessageBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbMessageBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbMessageBox)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbMessageBox)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbMessageBox)

/* Start stub implementations for class FXRbObjRegistry */

/* Start stub implementations for class FXRbObject */
IMPLEMENT_FXOBJECT_STUBS(FXRbObject)

/* Start stub implementations for class FXRbOption */
IMPLEMENT_FXOBJECT_STUBS(FXRbOption)
IMPLEMENT_FXID_STUBS(FXRbOption)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbOption)
IMPLEMENT_FXWINDOW_STUBS(FXRbOption)

/* Start stub implementations for class FXRbOptionMenu */
IMPLEMENT_FXOBJECT_STUBS(FXRbOptionMenu)
IMPLEMENT_FXID_STUBS(FXRbOptionMenu)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbOptionMenu)
IMPLEMENT_FXWINDOW_STUBS(FXRbOptionMenu)

/* Start stub implementations for class FXRbPCXIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbPCXIcon)
IMPLEMENT_FXID_STUBS(FXRbPCXIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPCXIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbPCXIcon)

/* Start stub implementations for class FXRbPCXImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbPCXImage)
IMPLEMENT_FXID_STUBS(FXRbPCXImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPCXImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbPCXImage)

/* Start stub implementations for class FXRbPNGIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbPNGIcon)
IMPLEMENT_FXID_STUBS(FXRbPNGIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPNGIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbPNGIcon)

/* Start stub implementations for class FXRbPNGImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbPNGImage)
IMPLEMENT_FXID_STUBS(FXRbPNGImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPNGImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbPNGImage)

/* Start stub implementations for class FXRbPPMIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbPPMIcon)
IMPLEMENT_FXID_STUBS(FXRbPPMIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPPMIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbPPMIcon)

/* Start stub implementations for class FXRbPPMImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbPPMImage)
IMPLEMENT_FXID_STUBS(FXRbPPMImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPPMImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbPPMImage)

/* Start stub implementations for class FXRbPacker */
IMPLEMENT_FXOBJECT_STUBS(FXRbPacker)
IMPLEMENT_FXID_STUBS(FXRbPacker)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPacker)
IMPLEMENT_FXWINDOW_STUBS(FXRbPacker)

/* Start stub implementations for class FXRbPicker */
IMPLEMENT_FXOBJECT_STUBS(FXRbPicker)
IMPLEMENT_FXID_STUBS(FXRbPicker)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPicker)
IMPLEMENT_FXWINDOW_STUBS(FXRbPicker)

/* Start stub implementations for class FXRbPopup */
IMPLEMENT_FXOBJECT_STUBS(FXRbPopup)
IMPLEMENT_FXID_STUBS(FXRbPopup)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPopup)
IMPLEMENT_FXWINDOW_STUBS(FXRbPopup)
IMPLEMENT_FXPOPUP_STUBS(FXRbPopup)

/* Start stub implementations for class FXRbPrintDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbPrintDialog)
IMPLEMENT_FXID_STUBS(FXRbPrintDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbPrintDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbPrintDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbPrintDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbPrintDialog)

/* Start stub implementations for class FXRbProgressBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbProgressBar)
IMPLEMENT_FXID_STUBS(FXRbProgressBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbProgressBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbProgressBar)

/* Start stub implementations for class FXRbProgressDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbProgressDialog)
IMPLEMENT_FXID_STUBS(FXRbProgressDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbProgressDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbProgressDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbProgressDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbProgressDialog)

/* Start stub implementations for class FXRbRGBIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbRGBIcon)
IMPLEMENT_FXID_STUBS(FXRbRGBIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRGBIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbRGBIcon)

/* Start stub implementations for class FXRbRGBImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbRGBImage)
IMPLEMENT_FXID_STUBS(FXRbRGBImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRGBImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbRGBImage)

/* Start stub implementations for class FXRbRadioButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbRadioButton)
IMPLEMENT_FXID_STUBS(FXRbRadioButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRadioButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbRadioButton)

/* Start stub implementations for class FXRbRealSlider */
IMPLEMENT_FXOBJECT_STUBS(FXRbRealSlider)
IMPLEMENT_FXID_STUBS(FXRbRealSlider)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRealSlider)
IMPLEMENT_FXWINDOW_STUBS(FXRbRealSlider)

/* Start stub implementations for class FXRbRealSpinner */
IMPLEMENT_FXOBJECT_STUBS(FXRbRealSpinner)
IMPLEMENT_FXID_STUBS(FXRbRealSpinner)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRealSpinner)
IMPLEMENT_FXWINDOW_STUBS(FXRbRealSpinner)
IMPLEMENT_FXREALSPINNER_STUBS(FXRbRealSpinner)

/* Start stub implementations for class FXRbRecentFiles */
IMPLEMENT_FXOBJECT_STUBS(FXRbRecentFiles)

/* Start stub implementations for class FXRbRegistry */
IMPLEMENT_FXOBJECT_STUBS(FXRbRegistry)

/* Start stub implementations for class FXRbReplaceDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbReplaceDialog)
IMPLEMENT_FXID_STUBS(FXRbReplaceDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbReplaceDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbReplaceDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbReplaceDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbReplaceDialog)

/* Start stub implementations for class FXRbRootWindow */
IMPLEMENT_FXOBJECT_STUBS(FXRbRootWindow)
IMPLEMENT_FXID_STUBS(FXRbRootWindow)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRootWindow)
IMPLEMENT_FXWINDOW_STUBS(FXRbRootWindow)

/* Start stub implementations for class FXRbRuler */
IMPLEMENT_FXOBJECT_STUBS(FXRbRuler)
IMPLEMENT_FXID_STUBS(FXRbRuler)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRuler)
IMPLEMENT_FXWINDOW_STUBS(FXRbRuler)

/* Start stub implementations for class FXRbRulerView */
IMPLEMENT_FXOBJECT_STUBS(FXRbRulerView)
IMPLEMENT_FXID_STUBS(FXRbRulerView)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbRulerView)
IMPLEMENT_FXWINDOW_STUBS(FXRbRulerView)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbRulerView)

#ifdef WITH_FXSCINTILLA

/* Start stub implementations for class FXRbScintilla */
IMPLEMENT_FXOBJECT_STUBS(FXRbScintilla)
IMPLEMENT_FXID_STUBS(FXRbScintilla)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbScintilla)
IMPLEMENT_FXWINDOW_STUBS(FXRbScintilla)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbScintilla)

#endif

/* Start stub implementations for class FXRbScrollArea */
IMPLEMENT_FXOBJECT_STUBS(FXRbScrollArea)
IMPLEMENT_FXID_STUBS(FXRbScrollArea)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbScrollArea)
IMPLEMENT_FXWINDOW_STUBS(FXRbScrollArea)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbScrollArea)

/* Start stub implementations for class FXRbScrollBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbScrollBar)
IMPLEMENT_FXID_STUBS(FXRbScrollBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbScrollBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbScrollBar)

/* Start stub implementations for class FXRbScrollCorner */
IMPLEMENT_FXOBJECT_STUBS(FXRbScrollCorner)
IMPLEMENT_FXID_STUBS(FXRbScrollCorner)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbScrollCorner)
IMPLEMENT_FXWINDOW_STUBS(FXRbScrollCorner)

/* Start stub implementations for class FXRbScrollPane */
IMPLEMENT_FXOBJECT_STUBS(FXRbScrollPane)
IMPLEMENT_FXID_STUBS(FXRbScrollPane)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbScrollPane)
IMPLEMENT_FXWINDOW_STUBS(FXRbScrollPane)
IMPLEMENT_FXPOPUP_STUBS(FXRbScrollPane)

/* Start stub implementations for class FXRbScrollWindow */
IMPLEMENT_FXOBJECT_STUBS(FXRbScrollWindow)
IMPLEMENT_FXID_STUBS(FXRbScrollWindow)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbScrollWindow)
IMPLEMENT_FXWINDOW_STUBS(FXRbScrollWindow)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbScrollWindow)

/* Start stub implementations for class FXRbSearchDialog */
IMPLEMENT_FXOBJECT_STUBS(FXRbSearchDialog)
IMPLEMENT_FXID_STUBS(FXRbSearchDialog)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSearchDialog)
IMPLEMENT_FXWINDOW_STUBS(FXRbSearchDialog)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbSearchDialog)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbSearchDialog)

/* Start stub implementations for class FXRbSeparator */
IMPLEMENT_FXOBJECT_STUBS(FXRbSeparator)
IMPLEMENT_FXID_STUBS(FXRbSeparator)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSeparator)
IMPLEMENT_FXWINDOW_STUBS(FXRbSeparator)

/* Start stub implementations for class FXRbHorizontalSeparator */
IMPLEMENT_FXOBJECT_STUBS(FXRbHorizontalSeparator)
IMPLEMENT_FXID_STUBS(FXRbHorizontalSeparator)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbHorizontalSeparator)
IMPLEMENT_FXWINDOW_STUBS(FXRbHorizontalSeparator)

/* Start stub implementations for class FXRbVerticalSeparator */
IMPLEMENT_FXOBJECT_STUBS(FXRbVerticalSeparator)
IMPLEMENT_FXID_STUBS(FXRbVerticalSeparator)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbVerticalSeparator)
IMPLEMENT_FXWINDOW_STUBS(FXRbVerticalSeparator)

/* Start stub implementations for class FXRbSettings */
IMPLEMENT_FXOBJECT_STUBS(FXRbSettings)

/* Start stub implementations for class FXRbShell */
IMPLEMENT_FXOBJECT_STUBS(FXRbShell)
IMPLEMENT_FXID_STUBS(FXRbShell)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbShell)
IMPLEMENT_FXWINDOW_STUBS(FXRbShell)

/* Start stub implementations for class FXRbShutterItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbShutterItem)
IMPLEMENT_FXID_STUBS(FXRbShutterItem)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbShutterItem)
IMPLEMENT_FXWINDOW_STUBS(FXRbShutterItem)

/* Start stub implementations for class FXRbShutter */
IMPLEMENT_FXOBJECT_STUBS(FXRbShutter)
IMPLEMENT_FXID_STUBS(FXRbShutter)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbShutter)
IMPLEMENT_FXWINDOW_STUBS(FXRbShutter)
IMPLEMENT_FXSHUTTER_STUBS(FXRbShutter)

/* Start stub implementations for class FXRbSlider */
IMPLEMENT_FXOBJECT_STUBS(FXRbSlider)
IMPLEMENT_FXID_STUBS(FXRbSlider)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSlider)
IMPLEMENT_FXWINDOW_STUBS(FXRbSlider)

/* Start stub implementations for class FXRbSpinner */
IMPLEMENT_FXOBJECT_STUBS(FXRbSpinner)
IMPLEMENT_FXID_STUBS(FXRbSpinner)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSpinner)
IMPLEMENT_FXWINDOW_STUBS(FXRbSpinner)
IMPLEMENT_FXSPINNER_STUBS(FXRbSpinner)

/* Start stub implementations for class FXRbSplashWindow */
IMPLEMENT_FXOBJECT_STUBS(FXRbSplashWindow)
IMPLEMENT_FXID_STUBS(FXRbSplashWindow)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSplashWindow)
IMPLEMENT_FXWINDOW_STUBS(FXRbSplashWindow)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbSplashWindow)

/* Start stub implementations for class FXRbSplitter */
IMPLEMENT_FXOBJECT_STUBS(FXRbSplitter)
IMPLEMENT_FXID_STUBS(FXRbSplitter)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSplitter)
IMPLEMENT_FXWINDOW_STUBS(FXRbSplitter)

/* Start stub implementations for class FXRbSpring */
IMPLEMENT_FXOBJECT_STUBS(FXRbSpring)
IMPLEMENT_FXID_STUBS(FXRbSpring)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSpring)
IMPLEMENT_FXWINDOW_STUBS(FXRbSpring)

/* Start stub implementations for class FXRbStatusBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbStatusBar)
IMPLEMENT_FXID_STUBS(FXRbStatusBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbStatusBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbStatusBar)

/* Start stub implementations for class FXRbStatusLine */
IMPLEMENT_FXOBJECT_STUBS(FXRbStatusLine)
IMPLEMENT_FXID_STUBS(FXRbStatusLine)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbStatusLine)
IMPLEMENT_FXWINDOW_STUBS(FXRbStatusLine)

/* Start stub implementations for class FXRbStream */
IMPLEMENT_FXSTREAM_STUBS(FXRbStream)

/* Start stub implementations for class FXRbFileStream */
IMPLEMENT_FXSTREAM_STUBS(FXRbFileStream)

/* Start stub implementations for class FXRbMemoryStream */
IMPLEMENT_FXSTREAM_STUBS(FXRbMemoryStream)

/* Start stub implementations for class FXRbStringDict */
IMPLEMENT_FXOBJECT_STUBS(FXRbStringDict)

/* Start stub implementations for class FXRbSwitcher */
IMPLEMENT_FXOBJECT_STUBS(FXRbSwitcher)
IMPLEMENT_FXID_STUBS(FXRbSwitcher)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbSwitcher)
IMPLEMENT_FXWINDOW_STUBS(FXRbSwitcher)

/* Start stub implementations for class FXRbTGAIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbTGAIcon)
IMPLEMENT_FXID_STUBS(FXRbTGAIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTGAIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbTGAIcon)

/* Start stub implementations for class FXRbTGAImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbTGAImage)
IMPLEMENT_FXID_STUBS(FXRbTGAImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTGAImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbTGAImage)

/* Start stub implementations for class FXRbTIFIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbTIFIcon)
IMPLEMENT_FXID_STUBS(FXRbTIFIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTIFIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbTIFIcon)

/* Start stub implementations for class FXRbTIFImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbTIFImage)
IMPLEMENT_FXID_STUBS(FXRbTIFImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTIFImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbTIFImage)

/* Start stub implementations for class FXRbTabBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbTabBar)
IMPLEMENT_FXID_STUBS(FXRbTabBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTabBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbTabBar)
IMPLEMENT_FXTABBAR_STUBS(FXRbTabBar)

/* Start stub implementations for class FXRbTabBook */
IMPLEMENT_FXOBJECT_STUBS(FXRbTabBook)
IMPLEMENT_FXID_STUBS(FXRbTabBook)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTabBook)
IMPLEMENT_FXWINDOW_STUBS(FXRbTabBook)
IMPLEMENT_FXTABBAR_STUBS(FXRbTabBook)

/* Start stub implementations for class FXRbTabItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbTabItem)
IMPLEMENT_FXID_STUBS(FXRbTabItem)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTabItem)
IMPLEMENT_FXWINDOW_STUBS(FXRbTabItem)

/* Start stub implementations for class FXRbTableItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbTableItem)
IMPLEMENT_FXTABLEITEM_STUBS(FXRbTableItem,FXTableItem)

/* Start stub implementations for class FXRbTable */
IMPLEMENT_FXOBJECT_STUBS(FXRbTable)
IMPLEMENT_FXID_STUBS(FXRbTable)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTable)
IMPLEMENT_FXWINDOW_STUBS(FXRbTable)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbTable)
IMPLEMENT_FXTABLE_STUBS(FXRbTable,FXTable)

/* Start stub implementations for class FXRbText */
IMPLEMENT_FXOBJECT_STUBS(FXRbText)
IMPLEMENT_FXID_STUBS(FXRbText)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbText)
IMPLEMENT_FXWINDOW_STUBS(FXRbText)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbText)
IMPLEMENT_FXTEXT_STUBS(FXRbText)

/* Start stub implementations for class FXRbTextField */
IMPLEMENT_FXOBJECT_STUBS(FXRbTextField)
IMPLEMENT_FXID_STUBS(FXRbTextField)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTextField)
IMPLEMENT_FXWINDOW_STUBS(FXRbTextField)

/* Start stub implementations for class FXRbToggleButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbToggleButton)
IMPLEMENT_FXID_STUBS(FXRbToggleButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbToggleButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbToggleButton)

/* Start stub implementations for class FXRbToolBar */
IMPLEMENT_FXOBJECT_STUBS(FXRbToolBar)
IMPLEMENT_FXID_STUBS(FXRbToolBar)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbToolBar)
IMPLEMENT_FXWINDOW_STUBS(FXRbToolBar)
IMPLEMENT_FXDOCKBAR_STUBS(FXRbToolBar)

/* Start stub implementations for class FXRbToolBarGrip */
IMPLEMENT_FXOBJECT_STUBS(FXRbToolBarGrip)
IMPLEMENT_FXID_STUBS(FXRbToolBarGrip)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbToolBarGrip)
IMPLEMENT_FXWINDOW_STUBS(FXRbToolBarGrip)

/* Start stub implementations for class FXRbToolBarShell */
IMPLEMENT_FXOBJECT_STUBS(FXRbToolBarShell)
IMPLEMENT_FXID_STUBS(FXRbToolBarShell)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbToolBarShell)
IMPLEMENT_FXWINDOW_STUBS(FXRbToolBarShell)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbToolBarShell)

/* Start stub implementations for class FXRbToolBarTab */
IMPLEMENT_FXOBJECT_STUBS(FXRbToolBarTab)
IMPLEMENT_FXID_STUBS(FXRbToolBarTab)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbToolBarTab)
IMPLEMENT_FXWINDOW_STUBS(FXRbToolBarTab)

/* Start stub implementations for class FXRbToolTip */
IMPLEMENT_FXOBJECT_STUBS(FXRbToolTip)
IMPLEMENT_FXID_STUBS(FXRbToolTip)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbToolTip)
IMPLEMENT_FXWINDOW_STUBS(FXRbToolTip)

/* Start stub implementations for class FXRbTopWindow */
IMPLEMENT_FXOBJECT_STUBS(FXRbTopWindow)
IMPLEMENT_FXID_STUBS(FXRbTopWindow)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTopWindow)
IMPLEMENT_FXWINDOW_STUBS(FXRbTopWindow)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbTopWindow)

/* Start stub implementations for class FXRbTranslator */
IMPLEMENT_FXOBJECT_STUBS(FXRbTranslator)
IMPLEMENT_FXTRANSLATOR_STUBS(FXRbTranslator)

/* Start stub implementations for class FXRbTreeItem */
IMPLEMENT_FXOBJECT_STUBS(FXRbTreeItem)
IMPLEMENT_FXTREEITEM_STUBS(FXRbTreeItem,FXTreeItem)

/* Start stub implementations for class FXRbTreeList */
IMPLEMENT_FXOBJECT_STUBS(FXRbTreeList)
IMPLEMENT_FXID_STUBS(FXRbTreeList)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTreeList)
IMPLEMENT_FXWINDOW_STUBS(FXRbTreeList)
IMPLEMENT_FXSCROLLAREA_STUBS(FXRbTreeList)
IMPLEMENT_FXTREELIST_STUBS(FXRbTreeList)

/* Start stub implementations for class FXRbTreeListBox */
IMPLEMENT_FXOBJECT_STUBS(FXRbTreeListBox)
IMPLEMENT_FXID_STUBS(FXRbTreeListBox)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTreeListBox)
IMPLEMENT_FXWINDOW_STUBS(FXRbTreeListBox)
IMPLEMENT_FXTREELISTBOX_STUBS(FXRbTreeListBox)

/* Start stub implementations for class FXRbTriStateButton */
IMPLEMENT_FXOBJECT_STUBS(FXRbTriStateButton)
IMPLEMENT_FXID_STUBS(FXRbTriStateButton)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbTriStateButton)
IMPLEMENT_FXWINDOW_STUBS(FXRbTriStateButton)

/* Start stub implementations for class FXRbVerticalFrame */
IMPLEMENT_FXOBJECT_STUBS(FXRbVerticalFrame)
IMPLEMENT_FXID_STUBS(FXRbVerticalFrame)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbVerticalFrame)
IMPLEMENT_FXWINDOW_STUBS(FXRbVerticalFrame)

/* Start stub implementations for class FXRbVisual */
IMPLEMENT_FXOBJECT_STUBS(FXRbVisual)
IMPLEMENT_FXID_STUBS(FXRbVisual)

/* Start stub implementations for class FXRbWindow */
IMPLEMENT_FXOBJECT_STUBS(FXRbWindow)
IMPLEMENT_FXID_STUBS(FXRbWindow)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbWindow)
IMPLEMENT_FXWINDOW_STUBS(FXRbWindow)

/* Start stub implementations for class FXRbWizard */
IMPLEMENT_FXOBJECT_STUBS(FXRbWizard)
IMPLEMENT_FXID_STUBS(FXRbWizard)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbWizard)
IMPLEMENT_FXWINDOW_STUBS(FXRbWizard)
IMPLEMENT_FXTOPWINDOW_STUBS(FXRbWizard)
IMPLEMENT_FXDIALOGBOX_STUBS(FXRbWizard)

/* Start stub implementations for class FXRbXBMIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbXBMIcon)
IMPLEMENT_FXID_STUBS(FXRbXBMIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbXBMIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbXBMIcon)

/* Start stub implementations for class FXRbXBMImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbXBMImage)
IMPLEMENT_FXID_STUBS(FXRbXBMImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbXBMImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbXBMImage)

/* Start stub implementations for class FXRbXPMIcon */
IMPLEMENT_FXOBJECT_STUBS(FXRbXPMIcon)
IMPLEMENT_FXID_STUBS(FXRbXPMIcon)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbXPMIcon)
IMPLEMENT_FXIMAGE_STUBS(FXRbXPMIcon)

/* Start stub implementations for class FXRbXPMImage */
IMPLEMENT_FXOBJECT_STUBS(FXRbXPMImage)
IMPLEMENT_FXID_STUBS(FXRbXPMImage)
IMPLEMENT_FXDRAWABLE_STUBS(FXRbXPMImage)
IMPLEMENT_FXIMAGE_STUBS(FXRbXPMImage)

